name: CI jobs for flutter, NextJS, and Express apps
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  PROJECT_NODE_VERSION: "22.11.0"
jobs:
  next-ci-tasks:
    runs-on: ubuntu-latest
    env:
      NEXT_PROJECT_PATH: ./
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node.js for Next.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.PROJECT_NODE_VERSION }}
      - name: Install dependencies for Next.js
        run: |
          cd ${{ env.NEXT_PROJECT_PATH }}
          npm install
      - name: Format and lint Next.js code
        run: |
          cd ${{ env.NEXT_PROJECT_PATH }}
          npm run format:chk
          npm run lint:chk
      - name: Build Next.js app
        run: |
          cd ${{ env.NEXT_PROJECT_PATH }}
          npm run build
